### ISSUE TITLE
No seek method for tokio implementation

### ISSUE THREAD

**Issue by coding-yogi** [gwierzchowski/csv-async#7]
I am using `tokio` as the runtime and from the src I notice that there is no seek method for tokio implementation. I tried a few things like seeking on the underlying reader as below, but it just sets the cursor to the start of the last record

```
reader.get_mut().seek(SeekFrom::Start(0)).await;
reader.read_record(&mut record).await
```
Is there any workaround for this? My use case is to start reading the file from the beginning after teh end of file

**Comment by gwierzchowski** [comment]
Yes. `seek` method is some extra add-on when you use `async-std`. There is no such method because tokio based AsyncRead trait does not provide it. I have limited time for work on this project currently (only some time during weekends) but will try to more deeply investigate this subject in next couple weeks.
For now the only one workaround that came to my mind is to reopen the file.

**Comment by gwierzchowski** [comment]
@coding-yogi  - please check, if you find time, if PR #9 address your needs.
I have added method `rewind` which is probably what you need.

**Comment by gwierzchowski** [comment]
Merged PR implements requested functionality
